imageupload/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('upload.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path

from . import views

app_name = 'upload'
urlpatterns = [
    # /
    path('', views.HomeView.as_view(), name='index'),
    path('fileupload/', views.fileupload, name='fileupload'),
    path('album/', views.AlbumView.as_view(), name='album'),
    path('album/delete/<int:id>', views.delete, name='delete'),
    path('album/edit/<int:pk>', views.EditView.as_view(), name="edit"),
    path('album/resize/', views.resize, name="resize"),

]

upload/models.py
from django.db import models

class ImageModel(models.Model):
    image_name = models.CharField(max_length=1000)
    image_date = models.DateTimeField()
    image_url = models.CharField(max_length=1000)

    def __str__(self):
        return self.image_name


class ImageDerivModel(models.Model):
    image_deriv_fk = models.ForeignKey(ImageModel, on_delete=models.CASCADE)
    image_name = models.CharField(max_length=1000)
    image_date = models.DateTimeField()
    image_url = models.CharField(max_length=1000)
    deriv_type = models.CharField(max_length=50)

    def __str__(self):
        return self.image_name

upload/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings
from .helper.imgDeriv import image_deriv
from .helper.file_validation import validation
from django.contrib import messages



from .models import ImageModel, ImageDerivModel

class HomeView(generic.TemplateView):
    template_name = 'upload/index.html'


    # def get(self, request):
    #     messages.success(request, 'test')
    #     return render(request, self.template_name)



class AlbumView(generic.ListView):
    model = ImageModel
    # paginate_by = 6
    template_name = 'upload/album.html'
    context_object_name = 'imagelist'


class EditView(generic.DetailView):
    model = ImageModel
    template_name = 'upload/edit.html'
    context_object_name = 'image'




def delete(request, id):
    d = ImageModel.objects.get(pk=id)
    name = d.image_name
    d.delete()
    os.remove(os.path.join(settings.MEDIA_ROOT, name))
    return HttpResponseRedirect(reverse('upload:album'))

@csrf_protect
def fileupload(request):
    fs = FileSystemStorage()
    for img in request.FILES.getlist('images'):
        if not validation(img.name):
            messages.error(request, 'Invalid File!')
            return HttpResponseRedirect(reverse('upload:index'))
        name = fs.save(img.name, img)
        file_url = fs.url(name)
        image_deriv(settings.MEDIA_ROOT + '\\' + name)
        orig_image = ImageModel(image_name=name, image_url=file_url, image_date=timezone.now())
        orig_image.save()
        list_of_edge = [
            "canny.jpg",
            "sobelx.jpg",
            "sobely.jpg",
            "sobel.jpg",
            "prewitt_x.jpg",
            "prewitt_y.jpg",
            "prewitt.jpg",
             ]

        for deriv_name in list_of_edge:
            split_name = name.split('.')[0] + '-' + deriv_name
            m = ImageDerivModel(
                image_deriv_fk=orig_image,
                image_name=split_name,
                image_date=timezone.now(),
                image_url='/media/%s' % split_name,
                deriv_type = deriv_name,
            )
            m.save()
        messages.success(request, 'Success')
    return HttpResponseRedirect(reverse('upload:index'))

# @csrf_protect
def resize(request):
    if request.method == 'POST':
        pass
    return HttpResponseRedirect(reverse('upload:album'))

#
#
# class UploadView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Question.objects.filter(
#         pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
#
#
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
#     def get_queryset(self):
#         """
#         Excludes any questions that aren't published yet.
#         """
#         return Question.objects.filter(pub_date__lte=timezone.now())
#
#
# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

upload/templates/upload/album.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Image Tumbler</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'upload/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'upload/album.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div >

        <div class="cover-container d-flex p-3 mx-auto flex-column">
          <header class="masthead mb-auto">
            <div class="inner">
              <h3 class="masthead-brand">Image Thumbler</h3>
              <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'upload:index' %}">Home</a>
                <a class="nav-link active" href="{% url 'upload:album' %}">Albums</a>
              </nav>
            </div>
          </header>
        </div>

        <div class="d-flex p-3 mx-auto flex-column">
          <main role="main">

            <section class=" text-center">
              <div class="container">
                <h1 class="jumbotron-heading">Album</h1>
                <br />
                <br />
                <br />
              </div>
            </section>

              <div class="container">
                <div class="row">
                  {% for image in imagelist %}
                  <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                      <div class="thumbnail">
                        <img class="card-img-top pop" id="{{ image.pk }}" src="{{ image.image_url }}" alt="{{ image.image_name }}" style="cursor:pointer">
                      </div>
                      <div class="card-body">
                        <p class="card-text text-muted"><strong>{{ image.image_name|truncatechars:15 }}</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a class='btn-outline-secondary' href="{% url 'upload:edit' image.pk %}">Edit</a></button>
                            <button type="button"  class="btn btn-sm btn-outline-danger"><a class='btn-outline-danger' href="{% url 'upload:delete' image.pk %}">Delete</a></button>
                          </div>
                          <small class="text-muted">{{ image.image_date }}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}

                  </div>
              </div>

          </main>
        </div>

        <div class="cover-container d-flex p-3 mx-auto flex-column">
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>© Image Thumber 2019</p>
        </div>
      </footer>
    </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'upload/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'upload/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'upload/album.js' %}"></script>
  </body>
</html>

upload/templates/upload/edit.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Image Tumbler</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'upload/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'upload/edit.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div >

        <div class="cover-container d-flex p-3 mx-auto flex-column">
          <header class="masthead mb-auto">
            <div class="inner">
              <h3 class="masthead-brand">Image Thumbler</h3>
              <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'upload:index' %}">Home</a>
                <a class="nav-link active" href="{% url 'upload:album' %}">Albums</a>
              </nav>
            </div>
          </header>
        </div>

        <div class="d-flex p-3 mx-auto flex-column">
          <main role="main">

            <section class=" text-center">
              <div class="container">
                <h1 class="jumbotron-heading">{{ image.image_name }}</h1>
                <br />
                <br />
                <br />
              </div>
            </section>

              <div class="container">
                <div class="row">
                  <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                      <div class="thumbnail">
                        <img class="card-img-top" id="{{ image.pk }}" src="{{ image.image_url }}" alt="{{ image.image_name }}" style="cursor:pointer">
                      </div>
                      <div class="card-body">
                        <p class="card-text text-muted"><strong>Original</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary btn-edit" data-toggle="modal" data-target="#myModal" id="{{ image.pk }}">Edit</button>
                            <!-- <button type="button"  class="btn btn-sm btn-outline-danger"><a class='btn-outline-danger' href="{% url 'upload:delete' image.pk %}">Delete</a></button> -->
                          </div>
                          <small class="text-muted">{{ image.image_date }}</small>
                        </div>
                      </div>
                    </div>
                  </div>

                    {% with image.imagederivmodel_set.all as images %}
                      {% for image in images %}
                        <div class="col-md-4">
                          <div class="card mb-4 box-shadow">
                            <div class="thumbnail">
                              <img class="card-img-top" id="{{ image.pk }}" src="{{ image.image_url }}" alt="{{ image.image_name }}" style="cursor:pointer">
                            </div>
                            <div class="card-body">
                              <p class="card-text text-muted"><strong>{{ image.deriv_type }}</strong></p>
                              <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                  <button type="button" class="btn btn-sm btn-outline-secondary btn-edit" data-toggle="modal" data-target="#myModal" id="{{ image.pk }}">Edit</button>
                                  <!-- <button type="button"  class="btn btn-sm btn-outline-danger"><a class='btn-outline-danger' href="{% url 'upload:delete' image.pk %}">Delete</a></button> -->
                                </div>
                                <small class="text-muted">{{ image.image_date }}</small>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                    {% endwith %}

                    <!-- The Modal -->
                    <div class="modal show fade" id="myModal">
                      <div class="modal-dialog">
                        <div class="modal-content">

                          <!-- Modal Header -->
                          <div class="modal-header">
                            <h4 class="modal-title">Modal Heading</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                          </div>

                          <!-- Modal body -->
                          <div class="modal-body">
                            <form id="imageEditor" method="post" action="{% url 'upload:resize' %}">
                              {% csrf_token %}
                              <p>
                                <label for="height">Height</label>
                                <input type="number"  id="height" name='height' value=250>
                              </p>

                              <p>
                                  <label for="width">Width</label>
                                  <input  type="number" id="width"  name="width"  value=306>
                              </p>

                              <button type="button" class="btn btn-md btn-outline-secondary btn-edit" >Save</button>
                              <button type="reset" class="btn btn-md btn-outline-danger btn-edit" >Reset</button>
                            </form>
                          </div>

                          <!-- Modal footer -->
                          <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                          </div>

                        </div>
                      </div>
                    </div>


                </div>
              </div>

          </main>
        </div>

        <div class="cover-container d-flex p-3 mx-auto flex-column">
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>© Image Thumber 2019</p>
        </div>
      </footer>
    </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'upload/js/jquery-3.2.1.min.js' %} " ></script>
    <script src="{% static 'upload/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'upload/edit.js' %}"></script>
  </body>
</html>

upload/templates/upload/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Image Tumbler</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'upload/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'upload/cover.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Image Thumbler</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'upload:index' %}">Home</a>
            <a class="nav-link" href="{% url 'upload:album' %}">Albums</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert {{ msg.tags }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ msg }}
            </div>
          {% endfor %}
        {% endif %}
        <h1 class="cover-heading">Upload Your Memories</h1>
        <p class="lead">Image thumbler can upload multiple and edit your picture on your own.</p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-secondary" data-toggle="modal" data-target="#exampleModal">Start now</a>
        </p>
      </main>


      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Upload Files</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <div class="container mt-5">
                <form method="post" enctype="multipart/form-data" action="{% url 'upload:fileupload' %}" >
                  {% csrf_token %}
                  <div class="form-group">
                  <div class="form-group">
                    <div class="custom-file">
                      <input type="file" name="images" multiple class="custom-file-input" id="customFile">
                      <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                  </div>
                  <div class="form-group">
                    <button type="submit" name="upload" value="upload" id="upload" class="btn btn-block btn-dark"><i class="fa fa-fw fa-upload"></i> Upload</button>
                  </div>
                </form>
              </div>

            </div>

          </div>
          </div>
        </div>
      </div>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>© Image Thumber 2019</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'upload/js/jquery-3.2.1.min.js' %}" ></script>
    <script src="{% static 'upload/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'upload/cover.js' %}"></script>
  </body>
</html>